log_level = "debug" # default: info

[[monitor]]
name = "Example monitor"
interval = 60

[monitor.target]
path = "echo"
args = ["synthetic monitor test output"]
env = [ ["var1", "value1"], ["var2", "value2"] ]

[[monitor.level]]
name = "info"
errors_to_escalate = 1
reporters = ["splunk", "slack"] 

[[monitor.level]]
name = "warn"
errors_to_escalate = 1
reporters = ["splunk", "slack"]

[[monitor.level]]
name = "alert"
successes_to_clear = 2
reporters = ["splunk", "slack", "pagerduty"]

[splunk]
index = "example_index"
hec_token = "hec_token"
endpoint = "endpoint_url"

[slack]
webhook_url = "https://hooks.slack.com/services/AaBbCcDd"
report_template = """*Monitor: {{res.name}} [level: {{res.level_name}}*] 
*command:* {{ res.target }} 
*args:* {{ res.args }} 
*stdout:* {{ res.stdout }} 
*stderr:* {{ res.stderr }} 
*result:*{{ res.status }} 
*duration:* {{ res.duration }} Î¼s"""
clear_template = "*Monitor: {{res.name}} returned to baseline*"

[pagerduty]
endpoint = "endpoint_url"
routing_key = "service_integration_key"
